// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj1xbJDHSRsqNQdFQi4RUEFEj1PDqhHMI',
    appId: '1:760352664018:web:74b907bf43cb9b1100000b',
    messagingSenderId: '760352664018',
    projectId: 'primeiro-projeto-esms-12345',
    authDomain: 'primeiro-projeto-esms-12345.firebaseapp.com',
    storageBucket: 'primeiro-projeto-esms-12345.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuEkoMUuGbRuGYCqVaxzbH-mXRssR_Els',
    appId: '1:760352664018:android:75b34f42fa3bd6cd00000b',
    messagingSenderId: '760352664018',
    projectId: 'primeiro-projeto-esms-12345',
    storageBucket: 'primeiro-projeto-esms-12345.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLNPoGlqYzY68vLeUYXkkHg6BmCo8w8nY',
    appId: '1:760352664018:ios:8e482433a1e50ad600000b',
    messagingSenderId: '760352664018',
    projectId: 'primeiro-projeto-esms-12345',
    storageBucket: 'primeiro-projeto-esms-12345.firebasestorage.app',
    iosBundleId: 'com.example.firebaseflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLNPoGlqYzY68vLeUYXkkHg6BmCo8w8nY',
    appId: '1:760352664018:ios:8e482433a1e50ad600000b',
    messagingSenderId: '760352664018',
    projectId: 'primeiro-projeto-esms-12345',
    storageBucket: 'primeiro-projeto-esms-12345.firebasestorage.app',
    iosBundleId: 'com.example.firebaseflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDj1xbJDHSRsqNQdFQi4RUEFEj1PDqhHMI',
    appId: '1:760352664018:web:37088301a24bbb2c00000b',
    messagingSenderId: '760352664018',
    projectId: 'primeiro-projeto-esms-12345',
    authDomain: 'primeiro-projeto-esms-12345.firebaseapp.com',
    storageBucket: 'primeiro-projeto-esms-12345.firebasestorage.app',
  );
}
